use QLGV
go

-- Q50. Tìm những giáo viên có lương lớn hơn lương của tất cả giáo viên thuộc bộ môn “Hệ thống thông tin”
SELECT *
FROM GIAOVIEN
WHERE LUONG > ALL (SELECT LUONG FROM GIAOVIEN WHERE MABM = 'HTTT')


-- Q51. Cho biết tên khoa có đông giáo viên nhất
SELECT TENKHOA
FROM KHOA
WHERE (SELECT COUNT(*) FROM GIAOVIEN WHERE GIAOVIEN.MAKHOA = KHOA.MAKHOA) = 
(SELECT MAX(GV_COUNT) FROM (SELECT COUNT(*) AS GV_COUNT FROM GIAOVIEN GROUP BY MAKHOA) AS GV_COUNTS)


-- Q52. Cho biết họ tên giáo viên chủ nhiệm nhiều đề tài nhất
SELECT GIAOVIEN.HOTEN, COUNT(DETAI.CAPQL) AS COUNT_CNDT
FROM GIAOVIEN
JOIN DETAI ON GIAOVIEN.MAGV = DETAI.GVCNDT
GROUP BY GIAOVIEN.HOTEN
HAVING COUNT_CNDT = (SELECT MAX(COUNT_CNDT) FROM (SELECT COUNT(CAPQL) AS COUNT_CNDT FROM DETAI GROUP BY GVCNDT) AS CNDT_COUNTS)


-- Q53. Cho biết mã bộ môn có nhiều giáo viên nhất
SELECT MABM
FROM GIAOVIEN
GROUP BY MABM
HAVING COUNT(*) = (SELECT MAX(GV_COUNT) FROM (SELECT COUNT(*) AS GV_COUNT FROM GIAOVIEN GROUP BY MABM) AS GV_COUNTS)


-- Q54. Cho biết tên giáo viên và tên bộ môn của giáo viên tham gia nhiều đề tài nhất.
SELECT GIAOVIEN.HOTEN, BOMON.TENBM
FROM GIAOVIEN
JOIN THAMGIADT ON GIAOVIEN.MAGV = THAMGIADT.MAGV
JOIN DETAI ON THAMGIADT.MADT = DETAI.MADT
JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM
GROUP BY GIAOVIEN.HOTEN, BOMON.TENBM
HAVING COUNT(*) = (SELECT MAX(COUNT_GVDT) FROM (SELECT COUNT(*) AS COUNT_GVDT FROM THAMGIADT GROUP BY MAGV) AS GVDT_COUNTS)


-- Q55. Cho biết tên giáo viên tham gia nhiều đề tài nhất của bộ môn HTTT.
SELECT GIAOVIEN.HOTEN
FROM GIAOVIEN
JOIN THAMGIADT ON GIAOVIEN.MAGV = THAMGIADT.MAGV
JOIN DETAI ON THAMGIADT.MADT = DETAI.MADT
WHERE GIAOVIEN.MABM = 'HTTT'
GROUP BY GIAOVIEN.HOTEN
HAVING COUNT(*) = (SELECT MAX(COUNT_GVDT) FROM (SELECT COUNT(*) AS COUNT_GVDT FROM THAMGIADT JOIN GIAOVIEN ON THAMGIADT.MAGV = GIAOVIEN.MAGV WHERE GIAOVIEN.MABM = 'HTTT' GROUP BY MAGV) AS GVDT_COUNTS)

-- cách khác
SELECT GIAOVIEN.HOTEN, COUNT(*) AS SOLUONG
FROM GIAOVIEN
JOIN GVCNDT ON GIAOVIEN.MAGV = GVCNDT.MAGV
JOIN DETAI ON GVCNDT.MADT = DETAI.MADT
JOIN CHUDE ON DETAI.MACD = CHUDE.MACD
JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM
WHERE BOMON.TENBM = 'HTTT'
GROUP BY GIAOVIEN.HOTEN
ORDER BY SOLUONG DESC
LIMIT 1;



-- Q56. Cho biết tên giáo viên và tên bộ môn của giáo viên có nhiều người thân nhất.
SELECT NGUOI_THAN.TEN AS NGUOI_THAN, GIAOVIEN.HOTEN AS GIAOVIEN, BOMON.TENBM AS BOMON
FROM NGUOI_THAN
JOIN GIAOVIEN ON NGUOI_THAN.MAGV = GIAOVIEN.MAGV
JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM
WHERE NGUOI_THAN.MAGV IN (
    SELECT MAGV
    FROM NGUOI_THAN
    GROUP BY MAGV
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
LIMIT 1;


-- Q57. Cho biết tên trưởng bộ môn mà chủ nhiệm nhiều đề tài nhất.

SELECT BOMON.TRUONGBM AS TEN_TRUONG_BM, COUNT(DETAI.MADT) AS SO_DE_TAI_CHU_NHIEM
FROM BOMON
JOIN DETAI ON BOMON.MABM = DETAI.MABM
JOIN GIAOVIEN ON DETAI.GVCNDT = GIAOVIEN.MAGV
WHERE GIAOVIEN.GVQLCM = 'Chủ nhiệm'
GROUP BY BOMON.TRUONGBM
ORDER BY SO_DE_TAI_CHU_NHIEM DESC
LIMIT 1;

